# Generated by Django 5.1 on 2024-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangomedia_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mangopost",
            name="title",
            field=models.TextField(max_length=100, unique=True),
        ),
    ]
