# Generated by Django 5.1 on 2024-08-13 08:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mangomedia_app", "0002_alter_mangopost_title"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mangopost",
            name="author",
        ),
        migrations.AddField(
            model_name="mangopost",
            name="author",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
