# Generated by Django 4.2.13 on 2024-08-26 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mangomedia_app", "0003_remove_mangopost_author_mangopost_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mangopost",
            name="post",
        ),
        migrations.AddField(
            model_name="mangopost",
            name="content",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mangopost",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="mangopost",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="mangopost",
            name="author",
            field=models.ManyToManyField(
                related_name="mangoposts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="mangopost",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="mangomedia_app.mangopost",
                    ),
                ),
            ],
        ),
    ]
